[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

infra = { path = "../infra" }
